name: Cypress Frame Tests 
on: [push]
jobs: 
  cypress-run:
    runs-on: macos-latest
    steps: 
      - name: Install ffmpeg
         run: brew install ffmpeg
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.5.1
        with: 
          start: npm run test

      
      
   
  
